apiVersion: v1
kind: Service
metadata:
  name: single-service
spec:
  selector:
    app: single
  ports:
  - protocol: "TCP"
    name: registry
    port: 8080
    targetPort: 1980
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: single
spec:
  selector:
    matchLabels:
      app: single
  replicas: 1
  template:
    metadata:
      labels:
        app: single
    spec:
      containers:
      - name: single
        image: localhost:5000/single:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
