apiVersion: v1
kind: Service
metadata:
  name: double-container
spec:
  selector:
    app: double-container
  ports:
  - protocol: "TCP"
    name: registry
    port: 8080
    targetPort: 1980
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: double
spec:
  selector:
    matchLabels:
      app: double-container
  replicas: 1
  template:
    metadata:
      labels:
        app: double-container
    spec:
      containers:
      - name: portal
        image: localhost:5000/portal:secure
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
      - name: database
        image: localhost:5000/database:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 2021
