apiVersion: v1
kind: Service
metadata:
  name: single-pod
spec:
  selector:
    app: single-pod
  ports:
  - protocol: "TCP"
    name: registry
    port: 8080
    targetPort: 1980
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  selector:
    matchLabels:
      app: single-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: single-pod
    spec:
      containers:
      - name: master
        image: localhost:5000/master:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 999
      - name: slave
        image: localhost:5000/slave:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1000
